device: 0

misc:
  seed: 1

experiment:
  # image
  input_resolution: [224, 224]
  simclr_mlp: [512, 128, 512]
  simclr_temperature: 0.1

  # mix
  mvs_image: false
  mixgen: false
  mixgen_type: cat  # ori or cat
  mixgen_p: 0.1
  mixgen_ratio: 0.1
  temp: 0.07
  # loss
  nitc_ratio: 1.0
  nisc_ratio: 1.0
  ####
  ss: false
  ss_ratio: 0.4
  ####
  ritc: true
  ritc_eps: 1.0e-2
  ritc_ratio: 1.0
  risc_ratio: 1.0
  ####
  mlm: false
  mlm_ratio: 1.0
  cmt_depth: 4 # cross modal transformer self attn layers
  ####
  citc: false
  citc_lambda1: 0.25
  citc_lambda2: 0.25
  citc_ratio: 0.1
  ####
  id: false
  id_ratio: 1.0
  # text
  dropout: 0.05
  eda_alpha: 0.05
  back_trans: true
  backtrans_p: 0.1
  text_length: 77
  patch_size: 16  # CLIP-ViT-B-16

schedule:
  lr: 1.0e-4
  epoch: 5
  epoch_warmup: 1
  lr_start: 1.0e-6
  lr_end: 5.0e-6
  weight_decay: 0.02
  betas: [0.9, 0.98]
  eps: 1.0e-8

model:
  ckpt_type: pretrain  # pretrain / finetune_train / direct_test
  saved_path: 'checkpoint/'
  checkpoint: 'checkpoint/ViT-B-16.pt'    # e.g., '../../data/CLIP/ViT-B-16.pt'
  exp_name: 'Shared_Vit16_trimodal_token77_bz240_epoch5'
  use_gather: true
  softlabel_ratio: 0.5
  embed_dim: 512
  vocab_size: 49408
  middle_dim: 512
  dropout: 0.1
log:
  print_period: 50

data:
  dataset: Tri-PEDES
  batch_size: 60
  test_batch_size: 256
  num_workers: 8
  # anno_dir: '/data0/wxy_data/datasets/CUHK-PEDES/CUHK-PEDES' 
  anno_dir1: '/data0/wxy_data/datasets/CUHK-PEDES/CUHK-PEDES'
  anno_dir2: '/data0/wxy_data/datasets/ICFG-PEDES/ICFG-PEDES'
  anno_dir3: '/data0/wxy_data/datasets/RSTPReid/RSTPReid'

distributed:
  backend: nccl
  url: 'env://'
